---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Copyright CloudDog 2020. Configure base policies and roles for centralized DevOps management'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: DevOps
        Parameters:
          - DevOpsAccount
          - ArtifactsBucketName
          - ArtifactsKeyArn

    ParameterLabels:
      DevOpsAccount:
        default: DevOps Account Number
      ArtifactsBucketName:
        default: DevOps Account Artifacts Bucket Name
      ArtifactsKeyArn:
        default: DevOps Account KMS Key Arn

Parameters:
  DevOpsAccount:
    Default: '663954396164'
    Description: DevOps Account Number
    AllowedPattern: (^$|[0-9]{12})
    ConstraintDescription: "must be a valid account number or empty"
    Type: String

  ArtifactsBucketName:
    Description: Artifacts bucket name
    Type: String

  ArtifactsKeyArn:
    Description: Artifacts KMS Key Arn
    Type: String    

Resources:
  CloudFormationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - cloudformation.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/service-role/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  DeployerRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role that allows assume role by DevOps Account
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS:
              - !Sub "arn:aws:iam::${DevOpsAccount}:root"
          Action:
          - sts:AssumeRole
      Path: "/service-role/"

  DevOpsDeployerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: deployer_policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - cloudformation:*
          - iam:PassRole
          Resource: "*"
        - Effect: Allow
          Action:
          - ecs:DescribeServices
          - ecs:DescribeTaskDefinition
          - ecs:DescribeTasks
          - ecs:ListTasks
          - ecs:RegisterTaskDefinition
          - ecs:UpdateService
          Resource: "*"
        - Effect: Allow
          Action:
          - s3:Get*
          - s3:Put*
          Resource:
          - !Sub "arn:aws:s3:::${ArtifactsBucketName}/*"
        - Effect: Allow
          Action:
          - s3:ListBucket
          Resource:
          - !Sub "arn:aws:s3:::${ArtifactsBucketName}"
        - Effect: Allow
          Action:
          - kms:DescribeKey
          - kms:GenerateDataKey*
          - kms:Encrypt
          - kms:ReEncrypt*
          - kms:Decrypt
          Resource:
          - !Ref ArtifactsKeyArn

      Roles: 
        - !Ref DeployerRole

Outputs:
  CloudFormationRoleArn:
    Value: !GetAtt CloudFormationRole.Arn
    Description: CloudFormation Role used by DevOps Account
    Export:
      Name: 
        Fn::Sub: ${AWS::StackName}-CloudFormationRoleArn

  DeployerRoleArn:
    Value: !GetAtt DeployerRole.Arn
    Description: Deployer Role used by DevOps Account
    Export:
      Name: 
        Fn::Sub: ${AWS::StackName}-DeployerRoleArn        
